version: "3.9"

services:
  backend:
    build: ./backend
    image: back-end:1.0
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: front-end:1.0
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
